### ISSUE TITLE
Block count on block_start_screen

### ISSUE THREAD

**Issue by SantiGarciaG** [SantiGarciaG/iswsIII#1]
I want to let participants know what block number they are at but I can't quite manage to get this right (no surprise there eh!) My code changes are marked with [marked with the margin comment #BBBBBB

In the isws_exp.py file I tried to create a variable "blockNumero" to keep count of the blocks (see codelines 24 & 85) and update it incrementally as each block runs.

And the idea is to show this at the beginning of the block (therefore appended to the "block_start_screen"). I have attempted to create this text object in the UI file (see codeline 119 and the #BBBBBB) but clearly, as usual, I'm making some rockie mistake somewhere and I'm too stupid to notice what's wrong.

(Please help!)

**Comment by cherepaha** [comment]
You almost got it! One thing is that, as the text on your TextStim is not static throughout the experiment, you cannot set it once and for all during initialization. Rather, you would need to re-set the text every time you call show_block_start_screen(), like we did with the threshold stim. Take a look at the updated file isws_exp_ui.py, and let me know if you've any questions!

**Comment by cherepaha** [comment]
Oh, and block number is already tracked by `block_no` within `run_block()` and `i` within `run_experiment()`, so I took the liberty to remove your `blockNumero`, as much as I like the way it sounds!

**Comment by SantiGarciaG** [comment]
uhh,... I hate when the solution is that close and yet I fail to bloody see it! Thanks! ;-)
